A hack for running jobs on Polaris. (#180)
There's apparently a known issue with torchrun:
https://github.com/pytorch/pytorch/issues/77737
It does not work with virtual environments.

Trying the workaround of specifying 
```
python3 -m torch.distributed.launch
```

almost does the trick. However, this command silently adds an argument
to the command line which causes our config parsing to fail:
--local-rank

After updating our config parsing logic to ignore this arg, I finally
hit another terminal failure. Need to verify if this is expected with
only 40GB RAM:
```
 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB. GPU  has a total capacity of 39.39 GiB of which 723.00 MiB is free. Process 2518572 has 414.00 MiB memory in use. Including non-PyTorch memory, this process has 38.27 GiB memory in use. Of the allocated memory 36.55 GiB is allocated by PyTorch, and 53.25 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
Towards OPE-107, OPE-121