Fix loading registered pretrain datasets (#1005)
# Description

The integration test `tests/integration/train/test_custom_models.py` is
failing, but the root cause is that loading registered pretrain datasets
(`Salesforce/wikitext` in this case) has many issues. This PR gets this
test to pass.

This PR is a temporary fix to the issue, and we'll do a more in-depth
look later.

All encountered errors:

```
src/oumi/builders/data.py:301
>           dataset = dataset_class(
                split=dataset_params.split,
                subset=dataset_params.subset,
                dataset_path=dataset_params.dataset_path,
                tokenizer=tokenizer,
                trust_remote_code=dataset_params.trust_remote_code,
                **dataset_kwargs,
            )
E           TypeError: BasePretrainingDataset.__init__() missing 1 required keyword-only argument: 'seq_length'
```
Root cause: src/oumi/builders/data.py:88 sets `seq_length` in
`dataset_kwargs`, but it's run after we create the
`BasePretrainingDataset`.
Temp fix: Specify seq_length in dataset_kwargs in the test
Future permanent fix: Automatically set seq_length in dataset_kwargs for
BasePretrainingDataset initialization

```
src/oumi/builders/data.py:301
E       TypeError: BaseIterableDataset.__init__() missing 1 required keyword-only argument: 'dataset_name'
```
Root cause: We don't pass in dataset_name, which is required for
iterable datasets but not map datasets
Fix: Pass in dataset_name. Also make that param optional in
BaseIterableDataset since dataset_path is used in some other cases

```
src/oumi/core/datasets/base_iterable_dataset.py:109
E           AttributeError: 'WikiTextDataset' object has no attribute 'trust_remote_code
```
Fix: self.trust_remote_code = trust_remote_code. Also give the field a
default value.

```
src/oumi/builders/data.py:3``
E           TypeError: BaseIterableDataset.to_hf() got an unexpected keyword argument 'return_iterable'
```
Root cause: `return_iterable` arg is only on BaseMapDataset
Fix: Add it to BaseIterableDataset but require it to be True for now

```
src/oumi/builders/data.py:98
>   self.formatting_func = lambda x: x[dataset_text_field]
E   KeyError: 'text'
```
Root cause: Registered pretraining datasets are loaded with
BasePretrainingDataset, our class which does tokenization+packing.
However, our code is trying to wrap it with ConstantLengthDataset which
is trying to do the same thing.
Fix: Don't try to wrap in ConstantLengthDataset if we already packed the
data ourselves

TODO: 
- Automatically set seq_length in dataset_kwargs for
BasePretrainingDataset initialization
- Have BaesMapDataset and BaseIterableDataset inherit from a common
abstract class to ensure their fn interfaces are aligned?
- Error if we try to mix a registered and non-registered PT dataset

## Related issues

Towards OPE-824

## Before submitting

- [ ] This PR only changes documentation. (You can ignore the following
checks in that case)
- [x] Did you read the [contributor
guideline](https://github.com/oumi-ai/oumi/blob/main/CONTRIBUTING.md)
Pull Request guidelines?
- [x] Did you link the issue(s) related to this PR in the section above?
- [x] Did you add / update tests where needed?