Avoid TRL library issue
In case anyone runs into this error:

TypeError: Trainer.__init__() got an unexpected keyword argument 'processing_class'

TRL's latest update breaks us:
https://github.com/huggingface/trl/releases

The fix is to prevent TRL from upgrading:
"trl>=0.9.0,<0.12.2",