Package checking: Adding functionality for checking package versioning and fast failing (#1031)
# Description

<!--
Thank you for contributing to Oumi! Before sending your PR out for
review, please take a quick read through this template.

When your PR is merged, its title will appear in our release notes. Make
sure your title gives a clear description of your change!

After you've updated your title, please replace this section with a
detailed description of your change. Include as much context as possible
so your reviewers can easily understand *what* you're changing and
*why*.
The more information you provide, the faster we can review your change!
-->
<!--↓↓↓↓↓↓↓↓↓↓ Describe your change below ↓↓↓↓↓↓↓↓↓↓-->
Package checking: Adding functionality for checking package versioning
and fast failing

example runtime error
```
RuntimeError: The current evaluation cannot be launched because the lm_harness platform prerequisites for the specific task (leaderboard_ifeval) are not satisfied. In order to proceed, the following package(s) must be installed and have the correct version:
Package `nltk` version is 3.9.0 but >=3.9.1 is required. Please install version >=3.9.1.
Note that you can install all evaluation-related packages with the following command:
`pip install -e '.[evaluation]'`
```

<!--↑↑↑↑↑↑↑↑↑↑ Describe your change above ↑↑↑↑↑↑↑↑↑↑-->

## Related issues

<!--
Make sure to list any relevant related issues to your change. More often
than not this will be the single issue fixed by your PR.
-->
<!--↓↓↓↓↓↓↓↓↓↓ List your related issues below ↓↓↓↓↓↓↓↓↓↓-->

Fixes # N/A

<!--↑↑↑↑↑↑↑↑↑↑ List your related issues above ↑↑↑↑↑↑↑↑↑↑-->

## Before submitting

- [ ] This PR only changes documentation. (You can ignore the following
checks in that case)
- [ ] Did you read the [contributor
guideline](https://github.com/oumi-ai/oumi/blob/main/CONTRIBUTING.md)
Pull Request guidelines?
- [ ] Did you link the issue(s) related to this PR in the section above?
- [ ] Did you add / update tests where needed?

## Reviewers

At least one review from a member of `oumi-ai/oumi-staff` is required.

<!-- Add `oumi-ai/oumi-staff` as a reviewer when your PR is ready for
review.

You are also welcome to add individual members of `oumi-ai/oumi-staff`
as reviewers.

If no one has reviewed your PR after several days, feel free to add a
comment tagging specific reviewers.

 -->